import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>

        <ToastContainer
          autoClose={2000}
          closeButton={false}
          hideProgressBar
          closeOnClick
          rtl={false}
          position="top-right"
          pauseOnHover
          draggable={false}
        />
      </body>
    </html>
  );
}
